[workspace]

members = [
     "frontend/exporter",
     "frontend/exporter/options",
     "frontend/diagnostics",
     "cli/options",
     "cli/options/engine",
     "cli/subcommands",
     "cli/driver",
]
