site_name: hax
theme:
  name: material
  logo: static/img/logo.png
  # favicon: static/img/favicon.png
  palette:
    primary: indigo
    accent: indigo
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.sections
    - navigation.path
    - navigation.tabs
    - header.autohide
    - navigation.instant
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - glightbox
  - search
  - offline
  - mkdocs-nav-weight
  - blog
