[package]
name = "cargo-command"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-thir-export"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
escape_string= "0.1"
