[package]
name = "hax-lint"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private=true

[dependencies]
hax-diagnostics = { version = "=0.1.0", path = "../diagnostics" }
tracing.workspace = true

[dev-dependencies]
regex = "1"
lazy_static = "1.4"
assert_cmd = "2.0"
