[package]
name = "hax-frontend-exporter-options"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true

