[book]
authors = ["Franziskus Kiefer"]
language = "en"
multilingual = false
src = "src"
title = "hax"

[output.html]
mathjax-support = true
additional-css = ["static/custom.css", "static/see-fstar-extraction.css"]
additional-js = ["static/see-fstar-extraction.js"]
