on:
  pull_request:

jobs:
  charon:
    runs-on: linux
    steps:
      - if: runner.environment == 'github-hosted'
        uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v4
        with:
          repository: AeneasVerif/charon
      - run: |
          cd charon
          cargo update -p hax-frontend-exporter --precise ${{ github.sha }}
          cargo update -p hax-frontend-exporter-options --precise ${{ github.sha }}
      - run: nix build -L
