name: Test building the Dockerfile

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build -f .docker/Dockerfile . -t hacspec-v2
